#!/usr/bin/env node
/* Generates everything derived from the designer templates:
     designer/js/templates.js          the templates, for the browser (works from file://)
     resources/<job>.job.yml           the Databricks Asset Bundle jobs
     designer/dist/pipeline-designer.html   a single self-contained file (not committed)
   Usage: node designer/scripts/build.js [--check]   (--check fails if committed files are out of date) */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..', '..');
const D = path.join(ROOT, 'designer');
['catalog', 'yaml', 'graph', 'bundle'].forEach(m => require(path.join(D, 'js', `${m}.js`)));
const B2S = globalThis.B2S;

function templates() {
  const dir = path.join(D, 'templates');
  return fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort()
    .map(f => ({ file: `designer/templates/${f}`, design: JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')) }));
}

function generated() {
  const ts = templates(), out = {};
  out['designer/js/templates.js'] = '/* Generated from designer/templates/*.json by designer/scripts/build.js. Do not edit. */\n' +
    "(function (root) {\n  'use strict';\n  root.B2S = root.B2S || {};\n  root.B2S.TEMPLATES = " +
    JSON.stringify(ts.map(t => ({ file: t.file, design: t.design })), null, 1) + ";\n})(typeof window !== 'undefined' ? window : globalThis);\n";
  ts.forEach(t => { out[`resources/${t.design.job.key}.job.yml`] = B2S.bundle.toYaml(t.design, B2S.CATALOG, t.file); });
  return out;
}

const GENERATED = '# Generated by the Bronze to Served pipeline designer';

/* Generated job files with no template any more (a job was renamed or deleted). Hand-written files are left alone. */
function staleJobFiles() {
  const dir = path.join(ROOT, 'resources'), expected = generated();
  return fs.readdirSync(dir).filter(f => f.endsWith('.job.yml') && !(`resources/${f}` in expected)
    && fs.readFileSync(path.join(dir, f), 'utf8').startsWith(GENERATED)).map(f => `resources/${f}`);
}

function singleFile() {
  let html = fs.readFileSync(path.join(D, 'index.html'), 'utf8');
  html = html.replace(/<link rel="stylesheet" href="(css\/[^"]+)">/g, (_, href) => `<style>\n${fs.readFileSync(path.join(D, href), 'utf8')}</style>`);
  html = html.replace(/<script src="(js\/[^"]+)"><\/script>/g, (_, src) => `<script>\n${fs.readFileSync(path.join(D, src), 'utf8').replace(/<\/script/gi, '<\\/script')}</script>`);
  return html;
}

if (require.main === module) {
  const check = process.argv.includes('--check');
  const files = generated();
  let stale = 0;
  for (const [rel, text] of Object.entries(files)) {
    const file = path.join(ROOT, rel);
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (current === text) continue;
    if (check) { stale += 1; console.log(`out of date: ${rel}`); } else { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, text); console.log(`wrote ${rel}`); }
  }
  for (const rel of staleJobFiles()) {
    if (check) { stale += 1; console.log(`no longer generated by any template: ${rel}`); } else { fs.unlinkSync(path.join(ROOT, rel)); console.log(`removed ${rel}`); }
  }
  if (!check && fs.existsSync(path.join(D, 'index.html'))) {
    fs.mkdirSync(path.join(D, 'dist'), { recursive: true });
    fs.writeFileSync(path.join(D, 'dist', 'pipeline-designer.html'), singleFile());
    console.log('wrote designer/dist/pipeline-designer.html');
  }
  if (check && stale) { console.log('run: node designer/scripts/build.js'); process.exit(1); }
  if (check) console.log(`all ${Object.keys(files).length} generated files are up to date`);
}
module.exports = { generated, templates, staleJobFiles };
